### ISSUE TITLE
Add a complete migration suite

### ISSUE THREAD

**Issue by eaigner** [eaigner/hood#5]
A la `rake db:migrate`

**Comment by liamstask** [comment]
Hi! Great project - the level of abstraction seems to be a good tradeoff between productivity and low level control, and the ability to opt in/out easily is great.

I've been working on https://bitbucket.org/liamstask/goose which provides a bare bones driver for running migrations. I'd like to provide some kind of compatibility with hood, such that migrations could be written using hood, and run via goose.

goose currently supports running .go files as migrations, though it currently exposes an opened database/sql *Tx to the migration routines [like so](https://bitbucket.org/liamstask/goose/src/1232c87d8ec7fc3d269c97cf92882049b05ae38a/db-sample/migrations/003_and_again.go?at=master) in order to commit the new version to the DB in the same transaction as the rest of the migration. Though it looks like hood would prefer to have access to the *DB directly, if I understand correctly. I'd be happy to alter this interface if you have any ideas about how to make them easier to work with.

Anyhow, just thought I'd give a heads up at the very least. Cheers.

**Comment by eaigner** [comment]
@liamstask I've begun implementing a migration suite for Hood modeled after active record (still early api, will be probably changed).

```
$ go run migrate.go create:migration AddUser
> 2013/01/06 14:25:47 created migration migrations/AddUser_1357478747.go
```

I looked through your source and it seems there would be a little bit of effort required to make it hood compatible, since it's based on raw SQL.

What do you mean by "hood would prefer to have access to the *DB directly"?

**Comment by liamstask** [comment]
@eaigner Ah, my project aims to handle both raw SQL and Go migrations. See [here](https://bitbucket.org/liamstask/goose/src/77a038291446f9154efe6e69a044f0cc9e3fd186/db-sample/migrations/003_and_again.go?at=master).

Since the database/sql *Tx is passed into the Up() and Down() routines here, I was wondering how best to allow users to create a hood instance within these types of migration scripts.

From my reading of the hood sources, it looked like one could not create a hood instance without the *DB, which was the basis of my comment.

It may be that I just need to pass in the *DB itself, rather than a *Tx, though that makes it slightly messier since it's no longer so simple to provide the atomicity of executing the entire migration within a transaction.

Thoughts?

**Comment by eaigner** [comment]
Yes, you are right. At the moment you have to pass the `Db` object to **hood**, if you look at the [New](https://github.com/eaigner/hood/blob/3dd08895e0f3106c9cf1df2c86af82cf52f8998f/hood.go#L220) function.

This is, because hood needs ad `sql.Db` reference for starting transactions (see [Begin](https://github.com/eaigner/hood/blob/3dd08895e0f3106c9cf1df2c86af82cf52f8998f/hood.go#L270))

**Comment by liamstask** [comment]
Got it, thanks for confirming.

Do you have any plans on how you'll manage the atomicity of migrations in your tool? Curious to get a sense of how else to guarantee the integrity of the database when migrations might be executing an arbitrary number of transactions.

Would it ever make sense to allow a hood instance to be created from a pre-existing transaction to support this kind of behavior?

**Comment by eaigner** [comment]
But why do you need to access the `Tx` struct anyway?

Running db dependent SQL with an ORM doesn't make any sense.

**Comment by eaigner** [comment]
I plan to implement it in such a way

```
func (m *Migration) Up(hd *hood.Hood) {
    // hd is a transactional hood object created with Begin() which is Commit()'ed
    // after the Up function is executed
    hd.CreateTable(&myTable{})
    hd.AddIndex(...)
    // and so on...
}
```

**Comment by liamstask** [comment]
I'm designing for the scenario in which users may want to use hood, another ORM, or any other database/sql compatible mechanism, within a migration script. I think sql.Tx is the common denominator for this usage.

In my case, the migration tool itself wants to access the Tx in order to insert the migration version into the database within the same transaction that the rest of the migration runs in. The migration tool already knows which SQL dialect the user has specified, so it can do this in a DB-appropriate way.

It would be nice, and conceptually clearer I think, if hood.Begin() returned a distinct hoodTx (or whatever) type that indicated that it's really a transaction and not a standard hood DB handle. If this transactional type could also be constructed from an existing sql.Tx, that would be extra tasty :)

I'd be happy to prototype such an approach, if that seemed interesting. What do you think?

**Comment by eaigner** [comment]
I'll see what I can do about the custom HoodTx type.

**Comment by liamstask** [comment]
Rockin. Please let me know if I can assist in any way.

**Comment by eaigner** [comment]
A basic migration suite is now implemented, see the new README on the repo page.
