### ISSUE TITLE
can't call functions on where close

### ISSUE THREAD

**Issue by mattetti** [eaigner/hood#63]
I was hoping to use the following code:

```
hood.Where("lower(username)", "=", "eaigner").Limit(1).Find(&user)
```

But it looks like hood is quoting the first argument resulting in a bad query (MySQL).

**Comment by eaigner** [comment]
You have to use the raw query methods for that, e.g. [Query](http://godoc.org/github.com/eaigner/hood#Hood.Query).
Or if you need more flexibility altogether, you can use [jet](https://github.com/eaigner/jet) instead of hood.

**Comment by mattetti** [comment]
Thanks, I tried to use jet, but it didn't like when I was mapping a record containing some null values. I figured Hood might be a better choice.

**Comment by eaigner** [comment]
Fixed the null issue just yesterday ;) https://github.com/eaigner/jet/commit/35377419b411fa9411a6be88c21b6dd180af4890

**Comment by mattetti** [comment]
w00t confirmed, I'm back on jet, thanks!

**Comment by eaigner** [comment]
Feel free to report issues ;)

Btw. another heads up. If you're using the https://github.com/go-sql-driver/mysql driver, I experienced hangs when you run a `Rows(&v)` on a query that doesn't return rows.

Seems to be driver specific. Got some hints from the dev how to work around this, but it's not in the repo yet.

So just call `Run()` instead of `Rows()` on a query that doesn't return rows to avoid this hiccup.

**Comment by mattetti** [comment]
I was reading the thread about Revel + Jet since that's what I'm using. I
noticed the discussion around github.com/go-sql-driver/mysql I can live
with the hanging for now if you are looking into the issue.

One last question about jet, is there way to safely escape some variables
when building queries?
Ideally an API similar to the one you documented:

```

db.Query(`INSERT INTO "fruits" ( "name", "price" ) VALUES ( $1, $2 )`,
"banana", 2.99).Run()

```

but for non insert queries:

```
db.Query(`select * from users WHERE username = "$1"`, "eaigner").Rows(&user)
```

Thanks again for 2 great libs.
